spring.application.name=spring-boot-url-shortener

# For the Docker Compose support to prevent container from being started and stopped when we stop/start the server
#spring.docker.compose.lifecycle-management=start_only

spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.show-sql=true

# To prevent Hibernate LazyLoadingException when we have fields that are lazily loaded
# Instead, perform lef join or use @EntityGraph for lazily loaded fields instead of relying on this property(if set to true)
spring.jpa.open-in-view=false

#spring.jpa.hibernate.ddl-auto=update

# App Config
app.base-url=http://localhost:8080
app.default-expiry-in-days=30
app.validate-original-url=true
app.page-size=10

# Spring Security config if not configured SecurityFilterChain Bean
#spring.security.user.name=user
#spring.security.user.password=password
#spring.security.user.roles=USER